
/* Drop Indexes */

DROP INDEX IF EXISTS MAST_AUTH_ID;
DROP INDEX IF EXISTS MAST_USER_ID;
DROP INDEX IF EXISTS TBL_TRNS_LOG_ID;
DROP INDEX IF EXISTS TBL_TRNS_LOG_SEQ_ID;



/* Drop Tables */

DROP TABLE IF EXISTS MAST_DEVELOP_ACNT;
DROP TABLE IF EXISTS TBL_NEXT_TRNS_LOG;
DROP TABLE IF EXISTS MAST_ACNT;
DROP TABLE IF EXISTS MAST_ACNT_ROOT;
DROP TABLE IF EXISTS TBL_CUST_APP;
DROP TABLE IF EXISTS MAST_APP;
DROP TABLE IF EXISTS MAST_AUTH;
DROP TABLE IF EXISTS MAST_CATEGORY;
DROP TABLE IF EXISTS MAST_CUST;
DROP TABLE IF EXISTS MAST_DEVELOP_REGIST;
DROP TABLE IF EXISTS TBL_TRNS_LOG;
DROP TABLE IF EXISTS TBL_DEVELOP_DETAILS_TRNS;
DROP TABLE IF EXISTS TBL_DEVELOP_DETAILS;
DROP TABLE IF EXISTS MAST_DEVELOP;
DROP TABLE IF EXISTS MAST_USER;




/* Create Tables */

CREATE TABLE MAST_ACNT
(
	ID SERIAL NOT NULL,
	ACNT_ROOT_ID CHAR(30) NOT NULL,
	ACNT_ID CHAR(30) NOT NULL UNIQUE,
	ACNT_ROOT_NAME CHAR(30) NOT NULL,
	-- 登録日
	INS_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_ACNT_ROOT
(
	ID SERIAL NOT NULL,
	ACNT_ROOT_ID CHAR(30) NOT NULL UNIQUE,
	ACNT_ROOT_NAME CHAR(30) NOT NULL,
	-- 登録日
	INS_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	-- 有効
	VALD INT DEFAULT -1,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_APP
(
	ID SERIAL NOT NULL,
	-- ディベロッパーID
	APP_ID CHAR(30) NOT NULL UNIQUE,
	APP_NAME CHAR(50) NOT NULL,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30) NOT NULL,
	IMAGE_PATH CHAR(255),
	IMAGE_PATH2 CHAR(255),
	IMAGE_PATH3 CHAR(255),
	URL CHAR(255),
	-- カテゴリーID
	CATEGORY_ID CHAR(30),
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	-- 公開開始日
	OPEN_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CLOSE_DT TIMESTAMP,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_AUTH
(
	ID SERIAL NOT NULL,
	-- 権限ID
	AUTH_ID CHAR(30) NOT NULL UNIQUE,
	-- 権限名
	-- 
	AUTH_NAME CHAR(30),
	-- 有効
	VALD INT DEFAULT -1 NOT NULL,
	-- 権限タイプ(閲覧、読み書き)
	AUTH_TYPE CHAR(10),
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	NOTE TEXT,
	PRIMARY KEY (ID),
	UNIQUE (AUTH_ID)
) WITHOUT OIDS;


CREATE TABLE MAST_CATEGORY
(
	ID SERIAL NOT NULL,
	-- カテゴリーID
	CATEGORY_ID CHAR(30) NOT NULL UNIQUE,
	-- カテゴリー名
	CATEGORY_NAME CHAR(30),
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	-- 有効
	VALD INT DEFAULT -1,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_CUST
(
	ID SERIAL NOT NULL,
	-- 顧客ID
	CUST_ID CHAR(30) NOT NULL UNIQUE,
	CUST_NAME CHAR(30),
	-- カスタマーパスワード
	CUST_PASS CHAR(30),
	-- 有効
	VALD INT DEFAULT -1,
	-- カード番号
	CARD_NO CHAR(20),
	STATUS_ID CHAR(30),
	REGIST_TYPE INT,
	-- 有効期限
	CARD_EXPY CHAR(4),
	-- カード番号
	CARD_NAME CHAR(30),
	-- 有効期限月
	CARD_EXPM CHAR(2),
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_DEVELOP
(
	ID SERIAL NOT NULL UNIQUE,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30) NOT NULL UNIQUE,
	DEVELOP_NAME CHAR(30),
	-- 有効
	VALD INT DEFAULT -1,
	-- 登録タイプ
	REQ_TYPE INT DEFAULT -1,
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	DEVELOP_PASS CHAR(30) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_DEVELOP_ACNT
(
	ID SERIAL NOT NULL,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30),
	ACNT_ID CHAR(30) NOT NULL UNIQUE,
	-- 有効
	VALD INT,
	-- トランザクション件数手数料
	TRANS_CNT_FEE NUMERIC(10,2) DEFAULT 0 NOT NULL,
	TRANS_PRICE_FEE_AMOUNT NUMERIC(10,2) DEFAULT 0,
	TRANS_PRICE_FEE_PERCENT NUMERIC(10,2) DEFAULT 0,
	-- トランザクション件数の原価
	COST_CNT NUMERIC(10,2) DEFAULT 0,
	-- トランザクション金額の原価
	COST_PRICE NUMERIC(10,2) DEFAULT 0 NOT NULL,
	-- 登録日
	INS_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_DEVELOP_REGIST
(
	ID SERIAL NOT NULL,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30) NOT NULL UNIQUE,
	-- 氏名
	NAME CHAR(30),
	NAME_KANA CHAR(30),
	BIRTH_DATE DATE,
	TEL CHAR(30),
	ZIP CHAR(7),
	-- 都道府県
	PREFECTURE CHAR(10),
	-- 住所
	ADDR CHAR(255),
	-- 住所その他
	ADDR2 CHAR(255),
	-- 住所カナ
	ADDR_KANA CHAR(255),
	-- 住所その他カナ
	ADDR2_KANA CHAR(255),
	-- HPのURL
	HP_URL CHAR(255),
	COMP_NAME CHAR(255),
	COMP_NAME_KANA CHAR(255),
	-- 代表者名
	COMP_PRESIDENT CHAR(30),
	-- 担当者役職
	COMP_POST CHAR(30),
	-- 担当者名
	COMP_CHARGER CHAR(30),
	-- FAX番号
	FAX CHAR(30),
	-- 会社タイプ
	COMP_TYPE INT,
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	-- メールアドレス
	MAIL CHAR(255),
	NOTE TEXT,
	-- 口座種別
	BANK_ACNT_ITEM CHAR(30),
	-- 口座名義
	BANK_ACNT_NAME CHAR(30),
	-- 口座番号
	BANK_ACNT_NUM CHAR(30),
	-- 銀行支店名
	BANK_BRANCH_NAME CHAR(30),
	-- 銀行コード
	BANK_CODE CHAR(10),
	-- 口座種別
	BANK_TYPE CHAR(30),
	-- 銀行名
	BANK_NAME CHAR(30),
	-- 口座名義(カナ)
	BANK_NAME_KANA CHAR(30),
	-- 証明書写真画像
	BANK_AUTHOR_IMG CHAR(255),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MAST_USER
(
	ID SERIAL NOT NULL,
	-- ユーザーID
	USER_ID CHAR(30) NOT NULL UNIQUE,
	-- ユーザー名
	USER_NAME CHAR(30),
	-- 権限ID
	AUTH_ID CHAR(30),
	-- メールアドレス
	MAIL CHAR(255),
	MAIL2 CHAR(255),
	MAIL3 CHAR(255),
	USER_PASS CHAR(30) NOT NULL,
	-- 有効
	VALD INT DEFAULT -1,
	NOTE TEXT,
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TBL_CUST_APP
(
	ID SERIAL NOT NULL,
	-- 顧客ID
	CUST_ID CHAR(30) NOT NULL,
	-- アプリID
	APP_ID CHAR(30) NOT NULL,
	-- ステータスID
	STATUS_ID CHAR(30),
	-- コメント
	DESCRIPTION TEXT,
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TBL_DEVELOP_DETAILS
(
	ID SERIAL NOT NULL UNIQUE,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30),
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	PAY_DATE DATE,
	TOTAL_AMNT NUMERIC(10,2),
	TOTAL_CNT INT DEFAULT 0,
	MONTH_CHARGE NUMERIC(10,0),
	TOTAL_CANCEL_CNT INT DEFAULT 0,
	TOTAL_CANCEL_AMNT NUMERIC(10,2) DEFAULT 0,
	TAX NUMERIC(10,2),
	-- レート
	INP_RATE NUMERIC(10,2) DEFAULT 0,
	CURRENCY CHAR(10),
	-- 銀行コード
	BANK_CODE CHAR(10),
	-- 銀行支店名
	BANK_BRANCH_NAME CHAR(30),
	-- 口座番号
	BANK_ACNT_NUM CHAR(30),
	-- 口座名義
	BANK_ACNT_NAME CHAR(30),
	-- 口座種別
	BANK_ACNT_ITEM CHAR(30),
	-- 銀行名
	BANK_NAME CHAR(30),
	-- 口座種別
	BANK_TYPE CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TBL_DEVELOP_DETAILS_TRNS
(
	ID SERIAL NOT NULL UNIQUE,
	DETAILS_ID INT NOT NULL,
	-- トランザクションID
	TRANS_SEQ_ID CHAR(15) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


-- 次回決済を行うトランザクションのデータ
CREATE TABLE TBL_NEXT_TRNS_LOG
(
	ID SERIAL NOT NULL,
	ACNT_ROOT_ID CHAR(30) NOT NULL,
	ACNT_ID CHAR(30) NOT NULL,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30) NOT NULL,
	-- 顧客ID
	CUST_ID CHAR(30) NOT NULL,
	AMOUNT NUMERIC(10,2) NOT NULL,
	SETL_DATE DATE,
	-- 有効
	VALD INT,
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	NOTE TEXT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TBL_TRNS_LOG
(
	ID SERIAL NOT NULL,
	-- トランザクションID
	TRANS_SEQ_ID CHAR(15) NOT NULL UNIQUE,
	ACNT_ID CHAR(30) NOT NULL,
	-- ディベロッパーID
	DEVELOP_ID CHAR(30),
	-- 顧客ID
	CUST_ID CHAR(30),
	AMOUNT NUMERIC(10,2) NOT NULL,
	-- トランザクション件数の原価
	COST_CNT NUMERIC(10,2),
	-- トランザクション金額の原価
	COST_PRICE NUMERIC(10,2),
	-- トランザクション件数手数料
	TRANS_CNT_FEE NUMERIC(10,2),
	TRANS_PRICE_FEE_AMOUNT NUMERIC(10,2),
	TRANS_PRICE_FEE_PERCENT NUMERIC(10,2),
	SETL_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SETL_DATE DATE DEFAULT CURRENT_TIMESTAMP,
	-- アカウント固有のトランザクションID
	ACNT_TRNS_ID CHAR(100),
	-- 決済結果
	SETL_STAT INT DEFAULT 0,
	ACNT_ROOT_ID CHAR(30) NOT NULL,
	MSG CHAR(255),
	-- 登録日
	INS_DT TIMESTAMP,
	-- 登録者
	INS_USER CHAR(30),
	-- 変更日
	UPD_DT TIMESTAMP,
	-- 変更者
	UPD_USER CHAR(30),
	-- 削除日時
	DEL_DT TIMESTAMP,
	-- 削除者
	DEL_USER CHAR(30),
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE MAST_DEVELOP_ACNT
	ADD FOREIGN KEY (ACNT_ID)
	REFERENCES MAST_ACNT (ACNT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_NEXT_TRNS_LOG
	ADD FOREIGN KEY (ACNT_ID)
	REFERENCES MAST_ACNT (ACNT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MAST_ACNT
	ADD FOREIGN KEY (ACNT_ROOT_ID)
	REFERENCES MAST_ACNT_ROOT (ACNT_ROOT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_NEXT_TRNS_LOG
	ADD FOREIGN KEY (ACNT_ROOT_ID)
	REFERENCES MAST_ACNT_ROOT (ACNT_ROOT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_CUST_APP
	ADD FOREIGN KEY (APP_ID)
	REFERENCES MAST_APP (APP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MAST_APP
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES MAST_CATEGORY (CATEGORY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_CUST_APP
	ADD FOREIGN KEY (CUST_ID)
	REFERENCES MAST_CUST (CUST_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_NEXT_TRNS_LOG
	ADD FOREIGN KEY (CUST_ID)
	REFERENCES MAST_CUST (CUST_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MAST_APP
	ADD FOREIGN KEY (APP_ID)
	REFERENCES MAST_DEVELOP (DEVELOP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MAST_DEVELOP_ACNT
	ADD FOREIGN KEY (DEVELOP_ID)
	REFERENCES MAST_DEVELOP (DEVELOP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MAST_DEVELOP_REGIST
	ADD CONSTRAINT DEVELOP_REGIST FOREIGN KEY (DEVELOP_ID)
	REFERENCES MAST_DEVELOP (DEVELOP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_DEVELOP_DETAILS
	ADD FOREIGN KEY (DEVELOP_ID)
	REFERENCES MAST_DEVELOP (DEVELOP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_NEXT_TRNS_LOG
	ADD FOREIGN KEY (DEVELOP_ID)
	REFERENCES MAST_DEVELOP (DEVELOP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_DEVELOP_DETAILS_TRNS
	ADD FOREIGN KEY (DETAILS_ID)
	REFERENCES TBL_DEVELOP_DETAILS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TBL_TRNS_LOG
	ADD FOREIGN KEY (TRANS_SEQ_ID)
	REFERENCES TBL_DEVELOP_DETAILS_TRNS (TRANS_SEQ_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE INDEX MAST_AUTH_ID ON MAST_AUTH (ID, AUTH_ID);
CREATE INDEX MAST_USER_ID ON MAST_USER (ID, USER_ID);
CREATE INDEX TBL_TRNS_LOG_ID ON TBL_TRNS_LOG (ID);
CREATE INDEX TBL_TRNS_LOG_SEQ_ID ON TBL_TRNS_LOG (TRANS_SEQ_ID);



/* Comments */

COMMENT ON COLUMN MAST_ACNT.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_ACNT.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_ACNT.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_ACNT.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_ACNT.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_ACNT.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_ACNT_ROOT.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_ACNT_ROOT.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_ACNT_ROOT.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_ACNT_ROOT.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_ACNT_ROOT.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_ACNT_ROOT.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_ACNT_ROOT.VALD IS '有効';
COMMENT ON COLUMN MAST_APP.APP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN MAST_APP.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN MAST_APP.CATEGORY_ID IS 'カテゴリーID';
COMMENT ON COLUMN MAST_APP.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_APP.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_APP.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_APP.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_APP.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_APP.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_APP.OPEN_DT IS '公開開始日';
COMMENT ON COLUMN MAST_AUTH.AUTH_ID IS '権限ID';
COMMENT ON COLUMN MAST_AUTH.AUTH_NAME IS '権限名
';
COMMENT ON COLUMN MAST_AUTH.VALD IS '有効';
COMMENT ON COLUMN MAST_AUTH.AUTH_TYPE IS '権限タイプ(閲覧、読み書き)';
COMMENT ON COLUMN MAST_AUTH.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_AUTH.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_AUTH.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_AUTH.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_AUTH.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_AUTH.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_CATEGORY.CATEGORY_ID IS 'カテゴリーID';
COMMENT ON COLUMN MAST_CATEGORY.CATEGORY_NAME IS 'カテゴリー名';
COMMENT ON COLUMN MAST_CATEGORY.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_CATEGORY.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_CATEGORY.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_CATEGORY.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_CATEGORY.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_CATEGORY.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_CATEGORY.VALD IS '有効';
COMMENT ON COLUMN MAST_CUST.CUST_ID IS '顧客ID';
COMMENT ON COLUMN MAST_CUST.CUST_PASS IS 'カスタマーパスワード';
COMMENT ON COLUMN MAST_CUST.VALD IS '有効';
COMMENT ON COLUMN MAST_CUST.CARD_NO IS 'カード番号';
COMMENT ON COLUMN MAST_CUST.CARD_EXPY IS '有効期限';
COMMENT ON COLUMN MAST_CUST.CARD_NAME IS 'カード番号';
COMMENT ON COLUMN MAST_CUST.CARD_EXPM IS '有効期限月';
COMMENT ON COLUMN MAST_CUST.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_CUST.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_CUST.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_CUST.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_CUST.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_CUST.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_DEVELOP.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN MAST_DEVELOP.VALD IS '有効';
COMMENT ON COLUMN MAST_DEVELOP.REQ_TYPE IS '登録タイプ';
COMMENT ON COLUMN MAST_DEVELOP.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_DEVELOP.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_DEVELOP.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_DEVELOP.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.VALD IS '有効';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.TRANS_CNT_FEE IS 'トランザクション件数手数料';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.COST_CNT IS 'トランザクション件数の原価';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.COST_PRICE IS 'トランザクション金額の原価';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_DEVELOP_ACNT.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.NAME IS '氏名';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.PREFECTURE IS '都道府県';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.ADDR IS '住所';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.ADDR2 IS '住所その他';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.ADDR_KANA IS '住所カナ';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.ADDR2_KANA IS '住所その他カナ';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.HP_URL IS 'HPのURL';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.COMP_PRESIDENT IS '代表者名';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.COMP_POST IS '担当者役職';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.COMP_CHARGER IS '担当者名';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.FAX IS 'FAX番号';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.COMP_TYPE IS '会社タイプ';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.DEL_USER IS '削除者';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.MAIL IS 'メールアドレス';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_ACNT_ITEM IS '口座種別';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_ACNT_NAME IS '口座名義';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_ACNT_NUM IS '口座番号';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_BRANCH_NAME IS '銀行支店名';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_CODE IS '銀行コード';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_TYPE IS '口座種別';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_NAME IS '銀行名';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_NAME_KANA IS '口座名義(カナ)';
COMMENT ON COLUMN MAST_DEVELOP_REGIST.BANK_AUTHOR_IMG IS '証明書写真画像';
COMMENT ON COLUMN MAST_USER.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN MAST_USER.USER_NAME IS 'ユーザー名';
COMMENT ON COLUMN MAST_USER.AUTH_ID IS '権限ID';
COMMENT ON COLUMN MAST_USER.MAIL IS 'メールアドレス';
COMMENT ON COLUMN MAST_USER.VALD IS '有効';
COMMENT ON COLUMN MAST_USER.INS_DT IS '登録日';
COMMENT ON COLUMN MAST_USER.INS_USER IS '登録者';
COMMENT ON COLUMN MAST_USER.UPD_DT IS '変更日';
COMMENT ON COLUMN MAST_USER.UPD_USER IS '変更者';
COMMENT ON COLUMN MAST_USER.DEL_DT IS '削除日時';
COMMENT ON COLUMN MAST_USER.DEL_USER IS '削除者';
COMMENT ON COLUMN TBL_CUST_APP.CUST_ID IS '顧客ID';
COMMENT ON COLUMN TBL_CUST_APP.APP_ID IS 'アプリID';
COMMENT ON COLUMN TBL_CUST_APP.STATUS_ID IS 'ステータスID';
COMMENT ON COLUMN TBL_CUST_APP.DESCRIPTION IS 'コメント';
COMMENT ON COLUMN TBL_CUST_APP.INS_DT IS '登録日';
COMMENT ON COLUMN TBL_CUST_APP.INS_USER IS '登録者';
COMMENT ON COLUMN TBL_CUST_APP.UPD_DT IS '変更日';
COMMENT ON COLUMN TBL_CUST_APP.UPD_USER IS '変更者';
COMMENT ON COLUMN TBL_CUST_APP.DEL_DT IS '削除日時';
COMMENT ON COLUMN TBL_CUST_APP.DEL_USER IS '削除者';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.INP_RATE IS 'レート';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_CODE IS '銀行コード';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_BRANCH_NAME IS '銀行支店名';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_ACNT_NUM IS '口座番号';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_ACNT_NAME IS '口座名義';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_ACNT_ITEM IS '口座種別';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_NAME IS '銀行名';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS.BANK_TYPE IS '口座種別';
COMMENT ON COLUMN TBL_DEVELOP_DETAILS_TRNS.TRANS_SEQ_ID IS 'トランザクションID';
COMMENT ON TABLE TBL_NEXT_TRNS_LOG IS '次回決済を行うトランザクションのデータ';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.CUST_ID IS '顧客ID';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.VALD IS '有効';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.INS_DT IS '登録日';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.INS_USER IS '登録者';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.UPD_DT IS '変更日';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.UPD_USER IS '変更者';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.DEL_DT IS '削除日時';
COMMENT ON COLUMN TBL_NEXT_TRNS_LOG.DEL_USER IS '削除者';
COMMENT ON COLUMN TBL_TRNS_LOG.TRANS_SEQ_ID IS 'トランザクションID';
COMMENT ON COLUMN TBL_TRNS_LOG.DEVELOP_ID IS 'ディベロッパーID';
COMMENT ON COLUMN TBL_TRNS_LOG.CUST_ID IS '顧客ID';
COMMENT ON COLUMN TBL_TRNS_LOG.COST_CNT IS 'トランザクション件数の原価';
COMMENT ON COLUMN TBL_TRNS_LOG.COST_PRICE IS 'トランザクション金額の原価';
COMMENT ON COLUMN TBL_TRNS_LOG.TRANS_CNT_FEE IS 'トランザクション件数手数料';
COMMENT ON COLUMN TBL_TRNS_LOG.ACNT_TRNS_ID IS 'アカウント固有のトランザクションID';
COMMENT ON COLUMN TBL_TRNS_LOG.SETL_STAT IS '決済結果';
COMMENT ON COLUMN TBL_TRNS_LOG.INS_DT IS '登録日';
COMMENT ON COLUMN TBL_TRNS_LOG.INS_USER IS '登録者';
COMMENT ON COLUMN TBL_TRNS_LOG.UPD_DT IS '変更日';
COMMENT ON COLUMN TBL_TRNS_LOG.UPD_USER IS '変更者';
COMMENT ON COLUMN TBL_TRNS_LOG.DEL_DT IS '削除日時';
COMMENT ON COLUMN TBL_TRNS_LOG.DEL_USER IS '削除者';



